### ISSUE TITLE
Bug: Expects "master" to be main branch

### ISSUE THREAD

**Issue by OmgImAlexis** [codechecks/monorepo#83]
This doesn't seem to work with repos that use a different name for the main branch like "main".

```
➜  snoo-wrapped git:(main) ✗ npx codechecks
CodeChecks Client v.0.1.11
https://codechecks.io

Executing 1 codechecks files
Error: Command failed: /bin/sh -c git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

master

    at makeError (/Users/xo/code/OmgImAlexis/snoo-wrapped/node_modules/@codechecks/client/node_modules/execa/index.js:174:9)
    at /Users/xo/code/OmgImAlexis/snoo-wrapped/node_modules/@codechecks/client/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async LocalProvider.getShaForRef (/Users/xo/code/OmgImAlexis/snoo-wrapped/node_modules/@codechecks/client/dist/ci-providers/Local.js:60:17)
    at async LocalProvider.getPrInfo (/Users/xo/code/OmgImAlexis/snoo-wrapped/node_modules/@codechecks/client/dist/ci-providers/Local.js:55:22)
    at async Object.getConstExecutionContext (/Users/xo/code/OmgImAlexis/snoo-wrapped/node_modules/@codechecks/client/dist/getExecutionContext.js:41:18)
    at async main (/Users/xo/code/OmgImAlexis/snoo-wrapped/node_modules/@codechecks/client/dist/runner.js:37:32) {
  code: 128,
  stdout: 'master\n',
  stderr: "fatal: ambiguous argument 'master': unknown revision or path not in the working tree.\n" +
    "Use '--' to separate paths from revisions, like this:\n" +
    "'git <command> [<revision>...] -- [<file>...]'\n",
  failed: true,
  signal: null,
  cmd: '/bin/sh -c git rev-parse master',
  timedOut: false,
  killed: false
}
```

**Comment by OmgImAlexis** [comment]
To fix this replace the following.
 https://github.com/codechecks/monorepo/blob/ba52ad88a50898bf4ad246fd16ce5f7f7ada4034/packages/client/src/ci-providers/Local.ts#L63
 
With this.

```js
 sha: await this.getShaForRef((await execa.shell(`git symbolic-ref --short HEAD`)).stdout.trim()), 
```
